version: '3.8'

services:
  routeros:
    image: ilhamridho/routeros:latest
    container_name: routeros-container
    
    volumes:
      - ./scripts:/routeros/scripts
    entrypoint: ["/routeros/scripts/entrypoint.sh"]
